version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPO=$(aws ecr describe-repositories --repository-names toebeans --output text --query "repositories[0].repositoryUri")
      - IMAGE=$REPO:latest
  build:
    commands:
      - cd backend
      - docker build -t $IMAGE .
      - docker push $IMAGE
  post_build:
    commands:
      - printf '[{"name":"toebeans","imageUri":"%s"}]' $IMAGE > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
