version: "3.7"
services:
  app:
    build:
      context: .
      target: debugger
    environment:
      - APP_ENV=development
      - DB_NAME=toebeans
      - DB_USER=toebeans
      - DB_PASS=secret
      - DB_HOST=db
      - DB_PORT=3306
      - TZ=America/Vancouver
      - LOG_LEVEL=debug
    volumes:
      - ./:/go/src/github.com/gold-kou/ToeBeans:cached
      - /go/src/github.com/gold-kou/ToeBeans/.git
    networks:
      - backend
    ports:
      - 80:8080
    depends_on:
      - db
      - minio
  db:
    image: mysql:8.0.21
    volumes:
      - db:/var/lib/mysql
    tmpfs:
      - /var/lib/mysql,mode=755
      - /var/log/mysql,mode=755
    environment:
      - MYSQL_DATABASE=toebeans
      - MYSQL_USER=toebeans
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Vancouver
    networks:
      - backend
    ports:
      - 3306:3306
  minio:
    image: minio/minio:RELEASE.2020-10-03T02-19-42Z
    ports:
      - 9000:9000
    volumes:
      - "./.docker-compose-data/minio/data:/export"
      - "./.docker-compose-data/minio/config:/root/.minio"
    environment:
      MINIO_ACCESS_KEY: "MINIO_ACCESS_KEY"
      MINIO_SECRET_KEY: "MINIO_SECRET_KEY"
      MINIO_REGION: "us-east-1"
    entrypoint: sh
    command: -c 'mkdir -p /images/icons && /usr/bin/minio server /images'
    networks:
      - backend

networks:
  backend:

volumes:
  db:
