version: "3.7"
services:
  app:
    build:
      context: .
      target: debugger
    environment:
      - APP_ENV=development
      - DOMAIN=localhost:80
      - TZ=Asia/Tokyo
      - LOG_LEVEL=debug
      - JWT_SECRET_KEY=samplekey
      - CSRF_AUTH_KEY=abcdefghijklmnopqrstuvwxyz123456 # must be 32 length
      - DB_NAME=toebeansdb
      - DB_USER=toebeans
      - DB_PASSWORD=secret
      - DB_HOST=db
      - DB_PORT=3306
      - GOOGLE_APPLICATION_CREDENTIALS=secret/service-account.json
      - AWS_ACCESS_KEY=test_access_key # must not be real key
      - AWS_SECRET_KEY=test_secret_key # must not be real key
      - AWS_REGION=ap-​northeast-1
      - SYSTEM_EMAIL=no-reply@toebeans.tk
      - S3_BUCKET_POSTINGS=/toebeans-postings
      - S3_BUCKET_ICONS=//toebeans-icons
    volumes:
      - ./:/go/src/github.com/gold-kou/ToeBeans/backend:cached
      - /go/src/github.com/gold-kou/ToeBeans/backend/.git
    networks:
      - backend
    ports:
      - 80:80
    depends_on:
      - db
      - minio

  db:
    image: mysql:5.7
    volumes:
      - ./toebeans-sql/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./toebeans-sql/mysql/sql:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
    tmpfs:
      - /var/lib/mysql,mode=755
      - /var/log/mysql,mode=755
    environment:
      - MYSQL_DATABASE=toebeans
      - MYSQL_USER=toebeans
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Tokyo
    networks:
      - backend
    ports:
      - 3306:3306

  minio:
    image: minio/minio:RELEASE.2020-10-03T02-19-42Z
    volumes:
      - "./.docker-compose-data/minio/data:/export"
      - "./.docker-compose-data/minio/config:/root/.minio"
    environment:
      MINIO_ACCESS_KEY: test_access_key
      MINIO_SECRET_KEY: test_secret_key
      MINIO_REGION: ap-​northeast-1
    entrypoint: sh
    command: -c 'mkdir -p /images/icons && mkdir -p /images/postings && /usr/bin/minio server /images'
    networks:
      - backend
    ports:
      - 9000:9000

networks:
  backend:

volumes:
  db:
