/*
 * Toe Beans
 *
 * API reference of Toe Beans
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package http

// Like - like
type Like struct {

	// posting id
	PostingId int64 `json:"posting_id"`
}
