/*
 * Toe Beans
 *
 * API reference of Toe Beans
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package http

// Comment - posting comment
type Comment struct {

	// comment
	Comment string `json:"comment"`
}
