/*
 * Toe Beans
 *
 * API reference of Toe Beans
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package http

type RequestRegisterPosting struct {

	// the title of posting
	Title string `json:"title"`

	// posting image file of base64 encoded and zipped
	Image string `json:"image"`
}
