/*
 * Toe Beans
 *
 * API reference of Toe Beans
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package http

type RequestRegisterUser struct {

	// email
	Email string `json:"email"`

	// user_name
	UserName string `json:"user_name"`

	// password
	Password string `json:"password"`
}
