/*
 * Toe Beans
 *
 * API reference of Toe Beans
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package http

// ResponseGetCsrfToken - get csrf token
type ResponseGetCsrfToken struct {

	// csrf token
	CsrfToken string `json:"csrf_token"`
}
