/*
 * Toe Beans
 *
 * API reference of Toe Beans
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package http

import (
	"time"
)

type ResponseGetNotification struct {

	// acting user name
	VisitorName string `json:"visitor_name"`

	// only when action is like or comment
	PostingId int64 `json:"posting_id,omitempty"`

	// only when action is comment
	CommentId int64 `json:"comment_id,omitempty"`

	// action type
	ActionType string `json:"action_type,omitempty"`

	// datetime with TZ
	CreatedAt time.Time `json:"created_at"`
}
