/*
 * Toe Beans
 *
 * API reference of Toe Beans
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package http

type RequestChangePassword struct {

	// old password
	OldPassword string `json:"old_password"`

	// new password
	NewPassword string `json:"new_password"`
}
