/*
 * Toe Beans
 *
 * API reference of Toe Beans
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package http

type ResponseGetFollowState struct {

	// follow or not
	IsFollow bool `json:"is_follow"`
}
