/*
 * Toe Beans
 *
 * API reference of Toe Beans
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package http

// ResponseBadRequest - Bad Reqeust
type ResponseBadRequest struct {

	// status
	Status int32 `json:"status"`

	// message
	Message string `json:"message"`
}
