/*
 * Toe Beans
 *
 * API reference of Toe Beans
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package http

import (
	"time"
)

// ResponseGetUser - get user
type ResponseGetUser struct {

	// user name
	UserName string `json:"user_name"`

	// icon
	Icon string `json:"icon"`

	// self introduction
	SelfIntroduction string `json:"self_introduction"`

	// the total count of posting
	PostingCount int64 `json:"posting_count"`

	// the total count of like
	LikeCount int64 `json:"like_count"`

	// the total count of liked
	LikedCount int64 `json:"liked_count"`

	// the total count of follow
	FollowCount int64 `json:"follow_count"`

	// the total count of followed
	FollowedCount int64 `json:"followed_count"`

	// the datetime when the account is created
	CreatedAt time.Time `json:"created_at"`
}
