openapi: "3.0.3"
info:
  version: 1.0.0
  title: Toe Beans
  description: API reference of Toe Beans
  license:
    name: MIT
servers:
  - url: http://localhost:80
    description: local
  - url: will be written
    description: production
paths:
  /login:
    post:
      description: login
      operationId: login
      tags:
        - user
      requestBody:
        $ref: '#/components/requestBodies/login'
      responses:
        "200":
          description: return token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/token'
        "400":
          $ref: '#/components/responses/badRequest'
        "401":
          $ref: '#/components/responses/unauthorized'
        "500":
          $ref: '#/components/responses/internalServerError'
  /logout:
    post:
      description: logout
      operationId: logout
      tags:
        - user
      security:
        - bearerAuth: []
      responses:
        "200":
          $ref: '#/components/responses/simpleSuccess'
        "401":
          $ref: '#/components/responses/unauthorized'
        "500":
          $ref: '#/components/responses/internalServerError'
  /user:
    post:
      description: register user info
      operationId: registerUser
      tags:
        - user
      requestBody:
        $ref: '#/components/requestBodies/registerUser'
      responses:
        "200":
          description: return token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/token'
        "400":
          $ref: '#/components/responses/badRequest'
        "500":
          $ref: '#/components/responses/internalServerError'
    get:
      description: get a user info
      operationId: getUser
      tags:
        - user
      security:
        - bearerAuth: []
      parameters:
        - name: user_name
          in: query
          description: user name
          required: true
          schema:
            type: string
            example: sample-user
      responses:
        "200":
          $ref: '#/components/responses/getUser'
        "400":
          $ref: '#/components/responses/badRequest'
        "401":
          $ref: '#/components/responses/unauthorized'
        "500":
          $ref: '#/components/responses/internalServerError'
    delete:
      description: delete user info
      operationId: deleteUser
      tags:
        - user
      security:
        - bearerAuth: []
      responses:
        "200":
          $ref: '#/components/responses/simpleSuccess'
        "401":
          $ref: '#/components/responses/unauthorized'
        "500":
          $ref: '#/components/responses/internalServerError'
  /user/{user_name}:
    put:
      description: update user info
      operationId: updateUser
      tags:
        - user
      security:
        - bearerAuth: []
      parameters:
        - name: user_name
          schema:
            type: string
          in: path
          required: true
          example: sample-user
      requestBody:
        $ref: '#/components/requestBodies/updateUser'
      responses:
        "200":
          $ref: '#/components/responses/simpleSuccess'
        "400":
          $ref: '#/components/responses/badRequest'
        "401":
          $ref: '#/components/responses/unauthorized'
        "500":
          $ref: '#/components/responses/internalServerError'
  /user-activation/{user_name}/{activation_key}:
    put:
      description: activate user by email
      operationId: activateUser
      tags:
        - user
      parameters:
        - name: user_name
          schema:
            type: string
          in: path
          required: true
          example: sample-user
        - name: activation_key
          description: hashed key to activate the user
          schema:
            type: string
          in: path
          required: true
          example: '5e8ff9bf55ba3508199d22e984129be6'
      responses:
        "200":
          $ref: '#/components/responses/simpleSuccess'
        "400":
          $ref: '#/components/responses/badRequest'
        "500":
          $ref: '#/components/responses/internalServerError'
  /password-reset-email:
    post:
      description: send an email to reset password
      operationId: sendPasswordResetEmail
      tags:
        - user
      requestBody:
        $ref: '#/components/requestBodies/sendPasswordResetEmail'
      responses:
        "200":
          $ref: '#/components/responses/simpleSuccess'
        "400":
          $ref: '#/components/responses/badRequest'
        "500":
          $ref: '#/components/responses/internalServerError'
  /posting:
    post:
      description: register posting
      operationId: registerPosting
      tags:
        - posting
      requestBody:
        $ref: '#/components/requestBodies/registerPosting'
      responses:
        "200":
          $ref: '#/components/responses/simpleSuccess'
        "400":
          $ref: '#/components/responses/badRequest'
        "401":
          $ref: '#/components/responses/unauthorized'
        "500":
          $ref: '#/components/responses/internalServerError'
  /postings:
    get:
      description: get posting list
      operationId: getPostingList
      tags:
        - posting
      parameters:
        - name: page
          description: page number
          in: query
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
            example: 1
          style: form
          explode: true
        - name: per_page
          description: the number of return items per page
          in: query
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
            example: 50
          style: form
          explode: true
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  page:
                    description: page
                    type: integer
                    format: int64
                    minimum: 1
                    example: 1
                  postings:
                    description: list of posting
                    type: array
                    items:
                      type: object
                      properties:
                        posting_id:
                          type: integer
                          format: int64
                          description: id
                          example: 1
                        user_name:
                          type: string
                          description: user_name
                          example: sample_user
                        uploaded_at:
                          description: uploaded datetime with TZ
                          type: string
                          example: '2020-01-01T18:30:00+09:00'
                        title:
                          type: string
                          description: the title of posting
                          example: This is a sample posting.
                        image_url:
                          type: string
                          description: image url
                          example: 'https://s3-ap-northeast-1.amazonaws.com/sample_bucket/sample1.jpg'
                        liked:
                          type: integer
                          format: int64
                          description: the number of liked
                          example: 20
                      required:
                        - posting_id
                        - user_name
                        - uploaded_at
                        - title
                        - liked
        "400":
          $ref: '#/components/responses/badRequest'
        "401":
          $ref: '#/components/responses/unauthorized'
        "500":
          $ref: '#/components/responses/internalServerError'
  /posting/{id}:
    delete:
      description: delete posting
      operationId: deletePosting
      tags:
        - posting
      parameters:
        - name: id
          schema:
            type: integer
            format: int64
          in: path
          required: true
      responses:
        "200":
          $ref: '#/components/responses/simpleSuccess'
        "400":
          $ref: '#/components/responses/badRequest'
        "401":
          $ref: '#/components/responses/unauthorized'
        "500":
          $ref: '#/components/responses/internalServerError'
  /health:
    get:
      description: health check
      operationId: getHealth
      tags:
        - system
      responses:
        '200':
          $ref: '#/components/responses/simpleSuccess'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  # parameters:
  #   access-token:
  #     name: access-token
  #     in: header
  #     required: true
  #     schema:
  #       type: string
  #       format: byte
  requestBodies:
    login:
      description: login
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/login'
    registerUser:
      description: register user
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/registerUser'
    updateUser:
      description: update user
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/updateUser'
    sendPasswordResetEmail:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/email'
    registerPosting:
      description: register posting
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/registerPosting'
    deletePosting:
      description: delete posting
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/deletePosting'
  responses:
    getUser:
      description: get user
      content:
        'application/json':
          schema:
            $ref: '#/components/schemas/getUser'
    registerPosting:
      description: register posting
      content:
        'application/json':
          schema:
            $ref: '#/components/schemas/postingID'
    simpleSuccess:
      description: '200'
      content:
        'application/json':
          schema:
            $ref: '#/components/schemas/simpleSuccess'
    badRequest:
      description: '400'
      content:
        'application/json':
          schema:
            $ref: '#/components/schemas/badRequest'
    unauthorized:
      description: '401'
      content:
        'application/json':
          schema:
            $ref: '#/components/schemas/unauthorized'
    notFound:
      description: '404'
      content:
        'application/json':
          schema:
            $ref: '#/components/schemas/notFound'
    internalServerError:
      description: '500'
      content:
        'application/json':
          schema:
            $ref: '#/components/schemas/internalServerError'
  schemas:
    token:
      type: object
      properties:
        access_token:
          type: string
          description: token to request APIs
          example: rerlkjewlrewi.dsafodniq34noisdf.e68kljsf
      required:
        - access_token
    email:
      type: object
      properties:
        email:
          type: string
          description: email
          example: sample-user@gmail.com
    login:
      type: object
      properties:
        email:
          type: string
          description: email
          example: sample_user@gmail.com
        password:
          type: string
          description: password
          example: password1234
      required:
        - email
        - password
    registerUser:
      type: object
      properties:
        email:
          type: string
          description: email
          example: sample_user@gmail.com
        user_name:
          type: string
          description: user_name
          example: sample_user
        password:
          type: string
          description: password
          example: password1234
      required:
        - email
        - user_name
        - password
    getUser:
      description: get user
      type: object
      properties:
        user_name:
          description: user name
          type: string
          example: sample_user
      required:
        - user_name
    updateUser:
      type: object
      properties:
        password:
          type: string
          description: password
          example: password1234
        icon:
          description: icon image file of base64 encoded and zipped
          type: string
          format: byte
          example: 'GEsDBBQACAAIAJhjzE4AAAAAAAAAAAAAAAASABAAaU9TIOOBrueUu+WDjzIucG5nVVgMAKTALl1wcQBd9gEUAIy8B'
    registerPosting:
      type: object
      properties:
        title:
          type: string
          description: the title of posting
          example: This is a sample posting.
        image:
          type: string
          format: byte
          description: posting image file of base64 encoded and zipped
          example: 'GEsDBBQACAAIAJhjzE4AAAAAAAAAAAAAAAASABAAaU9TIOOBrueUu+WDjzIucG5nVVgMAKTALl1wcQBd9gEUAIy8B'
      required:
        - title
        - image
    postingID:
      type: object
      properties:
        id:
          description: posting id
          type: integer
          format: int64
          example: 1
    deletePosting:
      type: object
      properties:
        id:
          description: posting id
          type: integer
          format: int64
          example: 1
      required:
        - id
    simpleSuccess:
      description: Success
      type: object
      properties:
        status:
          description: status
          type: integer
          format: int64
          example: 200
        message:
          description: message
          type: string
          example: 'success'
      required:
        - status
        - message
    badRequest:
      description: Bad Reqeust
      type: object
      properties:
        status:
          description: status
          type: integer
          format: int64
          example: 400
        message:
          description: message
          type: string
          example: 'Bad Request'
      required:
        - status
        - message
    unauthorized:
      description: Unauthorized
      type: object
      properties:
        status:
          description: status
          type: integer
          format: int64
          example: 401
        message:
          description: message
          type: string
          example: 'Unauthorized'
      required:
        - status
        - message
    notFound:
      description: Not Found
      type: object
      properties:
        status:
          description: status
          type: integer
          format: int64
          example: 404
        message:
          description: message
          type: string
          example: 'Not Found'
      required:
        - status
        - message
    internalServerError:
      description: Internal Server Error
      type: object
      properties:
        status:
          description: status
          type: integer
          format: int64
          example: 500
        message:
          description: message
          type: string
          example: 'Internal Server Error'
      required:
        - status
        - message
tags:
  - name: user
    description: user
  - name: posting
    description: posting
  - name: system
    description: system operation