/*
 * Toe Beans
 *
 * API reference of Toe Beans
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package http

type RequestResetPassword struct {

	// user name
	UserName string `json:"user_name"`

	// password
	Password string `json:"password"`

	// hashed key for password reset
	PasswordResetKey string `json:"password_reset_key"`
}
