/*
 * Toe Beans
 *
 * API reference of Toe Beans
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package http

// Follow - follow
type Follow struct {

	// following user name
	FollowingUserName string `json:"following_user_name"`

	// followed user name
	FollowedUserName string `json:"followed_user_name"`
}
