/*
 * Toe Beans
 *
 * API reference of Toe Beans
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package http

// ResponseGetUser - get user
type ResponseGetUser struct {

	// user name
	UserName string `json:"user_name"`

	// email
	Email string `json:"email"`

	// icon
	Icon string `json:"icon"`

	// the total count of posting
	PostingCount int64 `json:"posting_count"`

	// the total count of like
	LikeCount int64 `json:"like_count"`

	// the total count of liked
	LikedCount int64 `json:"liked_count"`

	// the datetime when the account is created
	CreatedAt string `json:"created_at"`
}
