/*
 * Toe Beans
 *
 * API reference of Toe Beans
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package http

import (
	"time"
)

type ResponseGetPosting struct {

	// id
	PostingId int64 `json:"posting_id"`

	// user_name
	UserName string `json:"user_name"`

	// uploaded datetime with TZ. This means created_at in postings table.
	UploadedAt time.Time `json:"uploaded_at"`

	// the title of posting
	Title string `json:"title"`

	// image url
	ImageUrl string `json:"image_url,omitempty"`

	// the number of liked
	Liked int64 `json:"liked"`
}
