/*
 * Toe Beans
 *
 * API reference of Toe Beans
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package http

type ResponseGetComment struct {

	// user_name
	UserName string `json:"user_name"`

	// commented datetime with TZ. This means created_at in postings table.
	CommentedAt string `json:"commented_at"`

	// the content of comment
	Comment string `json:"comment"`
}
