/*
 * Toe Beans
 *
 * API reference of Toe Beans
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package http

type RequestUpdateUser struct {

	// password
	Password string `json:"password,omitempty"`

	// icon image file of base64 encoded and zipped
	Icon string `json:"icon,omitempty"`

	// self-introduction
	SelfIntroduction string `json:"self-introduction,omitempty"`
}
