/*
 * Toe Beans
 *
 * API reference of Toe Beans
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package http

// ResponseInternalServerError - Internal Server Error
type ResponseInternalServerError struct {

	// status
	Status int32 `json:"status"`

	// message
	Message string `json:"message"`
}
