name: openapi generated test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  openapi:
    name: openapi generated test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run shell
        run: ./backend/hack/openapi/check_openapi_generated.sh
