name: golangci-lint
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run lint
        run: make lint
        working-directory: ./backend
